### ISSUE TITLE
Bump up actions/setup-node@v3 to v4 on ui test workflow

### ISSUE THREAD

**Issue by 2wheeh** [MovieReviewComment/Mr.C#140]
### Contents
- 현재 ui-test workflow에서 이미 node v20을 사용중인데 아래의 warning이 발생합니다:
<img width="1222" alt="image" src="https://github.com/MovieReviewComment/Mr.C/assets/40269597/77ad145c-774a-47df-9fb8-5138a9921c06">

- api workflow와 동일하게 `actions/setup-node@v3` -> `actions/setup-node@v4` 변경 시 해당 warning이 사라지는 것을 확인했습니다.

**Comment by 2wheeh** [comment]
참고:
-  https://github.com/actions/setup-node/issues/850

**Comment by rwader-swi** [comment]
I updated my workflows like `node-version: 20` or even as` 'latest'`, and in the logs it downloads the .tar or gets from cache correctly. But on the workflow run's page I still get 'Node 16 deprecated' flooded warnings. Is there anything I'm missing?
<img width="184" alt="image" src="https://github.com/MovieReviewComment/Mr.C/assets/138435075/09f3bdf6-3a5d-4e12-9ce7-a48116d2e780">

**Comment by rwader-swi** [comment]
Also if u using the below, change action/setup-node to v4 and actions/github-script to v7 in ur entire repo
<img width="184" alt="image" src="https://github.com/MovieReviewComment/Mr.C/assets/138435075/3007c378-d80a-435b-89ba-d50612bf4cfd">
