### ISSUE TITLE
Fix logout api request header on Wiki

### ISSUE THREAD

**Issue by 2wheeh** [MovieReviewComment/Mr.C#176]
### Content
- [logout api 위키](https://github.com/MovieReviewComment/Mr.C/wiki/Auth#request-2) 요청 헤더 수정 요청 (`X-MRC-TOKEN -> Authorization`)

**Comment by skgndi12** [comment]
https://github.com/MovieReviewComment/Mr.C/wiki/Auth/5164b3d69977403e36ffa2e1119d333600fd65e5 에서 수정했습니다

**Comment by 2wheeh** [comment]
@skgndi12 네 수정감사합니다. 근데 현재 해당 api가 문서와 다르게 authorization 헤더 혹은 쿠키 없이 요청을 보내도 200번을 응답하는 듯 합니다.

<img width="670" alt="image" src="https://github.com/MovieReviewComment/Mr.C/assets/40269597/c3cd29c4-7b14-4f1b-a0da-b44c43b0136b">

`/api/users/self` 에서 처럼 401 Unauthorized 가 리턴되어야 하는거 아닌가요? 
의도된 동작이라면 문서의 headers, cookies 도 없애는게 맞을 것 같은데 확인부탁드립니다 ㅎㅎ

**Comment by skgndi12** [comment]
확인했습니다. 위키 문서에는 말씀하신 것처럼 인증 정보를 확인하도록 작성되어 있고, 실제 동작은 인증 정보 확인하지 않게끔 구현되어 있었습니다. 말씀하신 내용 확인하여 위키 문서의 내용대로 동작하게끔 수정했습니다. 반영은 https://github.com/MovieReviewComment/Mr.C/pull/178 에서 진행하고 있습니다.

**Comment by 2wheeh** [comment]
> 확인했습니다. 위키 문서에는 말씀하신 것처럼 인증 정보를 확인하도록 작성되어 있고, 실제 동작은 인증 정보 확인하지 않게끔 구현되어 있었습니다. 말씀하신 내용 확인하여 위키 문서의 내용대로 동작하게끔 수정했습니다. 반영은 https://github.com/MovieReviewComment/Mr.C/pull/178 에서 진행하고 있습니다.

확인 감사합니다!
