### ISSUE TITLE
Make nickname shorter

### ISSUE THREAD

**Issue by 2wheeh** [MovieReviewComment/Mr.C#210]
### Content
- 확인 결과, 뷰포트 너비가 가장 좁은 기종들(ex. Iphone 5/SE)의 경우 일정 길이 이상 긴 닉네임이 생성된 경우에 화면 너비를 초과하게 됩니다.
- `긍정적인 시네필 에메랄드빛 이구아나` 정도가 최대이고, `사랑스러운 시네필 에메랄드빛 바다코끼리` 같은 닉네임은 너무 깁니다.

    <img width="402" alt="image" src="https://github.com/MovieReviewComment/Mr.C/assets/40269597/a8384abd-38f6-4fa5-abff-688498d50b44">

1. 5자이상 단어들을 제외하거나 
2. 전체 길이에 대한 제한을 두고, 길이 초과 시 재생성을 시도

같은 방향으로 수정되면 좋을 것 같습니다. 어떻게 생각하시나요?

cc @skgndi12 @isutare412

**Comment by skgndi12** [comment]
@2wheeh 닉네임이 화면 너비를 초과한 경우 화면에는 어떻게 표시가 되나요?

**Comment by 2wheeh** [comment]
> @2wheeh 닉네임이 화면 너비를 초과한 경우 화면에는 어떻게 표시가 되나요?

스크롤과 불필요한 여백이 생기게 됩니다.

<img width="268" alt="image" src="https://github.com/MovieReviewComment/Mr.C/assets/40269597/014ccebf-31eb-49ec-9ce6-9a40758564a6">

근데 다시보니 iPhone 5/SE 는 그냥 SE 랑 다른 구형 모델이네요...
SE 만 되어도 현재 길이로 문제가 없어보입니다. 크기가 작은 구형 모바일기기들을 지원할 지에 대한 결정이 되겠네요.
전 그냥 유지해도 괜찮을 것 같습니다.

**Comment by skgndi12** [comment]
저도 유지하는 방향이면 좋을 것 같습니다!

**Comment by 2wheeh** [comment]
참고로 #209 수정 후 가장 긴 닉네임을 iPhone SE 에서 표시하는 경우입니다:

<img width="427" alt="image" src="https://github.com/MovieReviewComment/Mr.C/assets/40269597/c3b46fe4-4cbf-4017-b67c-4c2bb67dc739">

> 저도 유지하는 방향이면 좋을 것 같습니다!

네 이슈는 close 하겠습니다
