### ISSUE TITLE
Add total Item count on List Responses

### ISSUE THREAD

**Issue by 2wheeh** [MovieReviewComment/Mr.C#213]
list API 응답에 전체 아이템 수에 대한 필드 추가를 요청합니다.

- 현재 list API 의 응답에 pagination 관련해서 totalPageCount 가 담겨오지만, 페이지 수가 아닌 전체 아이템 수는 알 방법이 없습니다.
- 검색 결과나, 댓글의 수가 전체 몇개인지 모든 페이지에 대해서 요청을 보내지 않고도 아는 상황이 더 일반적인 방식으로 생각됩니다.

어떻게 생각하시나요?

cc @skgndi12 @isutare412

**Comment by skgndi12** [comment]
크게 수정해야 하는 내용이 아니라 괜찮습니다.

**Comment by skgndi12** [comment]
#218 의 내용을 보면서 혼동되는 부분이 있습니다. #218 이슈가 작업되면 리뷰에 작성된 총 댓글 수는 이제 리뷰 정보를 반환하는 모든 API 에서 포함되어 응답할 것 입니다. 그런데 현재 이슈에서 작성된 내용에 따르면 reply list API 에서도  totalEntryCount 라는 필드에 동일한 값이 설정되어 응답할 것인데 이 부분에 @2wheeh 님의 생각이 궁금합니다.

**Comment by 2wheeh** [comment]
> https://github.com/MovieReviewComment/Mr.C/issues/218 의 내용을 보면서 혼동되는 부분이 있습니다. https://github.com/MovieReviewComment/Mr.C/issues/218 이슈가 작업되면 리뷰에 작성된 총 댓글 수는 이제 리뷰 정보를 반환하는 모든 API 에서 포함되어 응답할 것 입니다. 그런데 현재 이슈에서 작성된 내용에 따르면 reply list API 에서도 totalEntryCount 라는 필드에 동일한 값이 설정되어 응답할 것인데 이 부분에 @2wheeh 님의 생각이 궁금합니다.

@skgndi12 #218 에 작성한 대로 둘은 같은 값이지만
 - `Review` Entity 에겐 관련이 큰 데이터이고, 
 - `ListReviewReply` 에겐 List APIs 에게 일반적으로 기대하는 전체 아이템의 수로서 의미 있는 데이터라고 생각합니다.

위의 이유로 Review 도메인의 API와 ListReviewReply API의 응답으로 둘 다 해당 값을 기대할 것이라고 생각합니다. 그런데 해당 값이 한쪽 API 응답에만 존재하는 상황이라고 한다면, 결국 두 API는 항상 같이 호출하게 됩니다.

따라서 해당 값이 양쪽에 존재하므로써, 두 API를 더 독립적으로 사용할 수 있을 것 같습니다.

예를들어 #218 대로 `Review` Entity 에 `replyCount` 가 추가되지 않는다면, `ListReviews` 를 호출하는 입장에선 List 에 같이 보여주고 싶은 필드(`replyCount`)가 없는 상황을 만나게됩니다. 결국 List UI 만을 위해 `ListReviews` 가 돌려준 `totalEntryCount` 수 만큼 `ListReviewReply` 를 함께 요청해야합니다.

반대로 `Review` Entity에 `replyCount` 가 있으니 `ListReviewReply` 에서  `totalEntryCount` 를 뺀다 -> 이렇게 되면 `ListReviewReply`를 요청하는 상황에서는 항상 `totalEntryCount` 에서 기대하는 값을 위해 항상 `GetReviewDetail` 을 같이 호출해야겠네요. 또한 다른 List API 들은 `totalEntryCount`을 응답하고 `ListReviewReply` 에서만 제외한다면 일관성이 없다고도 느껴집니다.

**Comment by skgndi12** [comment]
자세한 설명 감사합니다! @2wheeh 님의 말씀대로 중복된 정보지만 독립된 사용을 위해서라도 review 정보를 반환하는 API 와 list replies API 모두 같은 정보를 포함하는게 좋을 것 같네요.
