### ISSUE TITLE
Fix list comments API to parse query parameter

### ISSUE THREAD

**Issue by 2wheeh** [MovieReviewComment/Mr.C#219]
### Content

현재 List Comments API 에서 query parameter 를 파싱할때, 
pathname과 query parameter 사이에 구분자로 `?` 가 아니라 `/?`가 있어야 유효하다고 판단합니다. 

의도된 부분인지 확인 부탁드립니다.

### Current

<img width="543" alt="image" src="https://github.com/MovieReviewComment/Mr.C/assets/40269597/a171dc8d-a36b-45c0-a361-7a57bfd0fc74">

### Expected ?

```diff
- pathname/?query1=foo&query2=bar
+ pathname?query1=foo&query2=bar
```

cc @skgndi12 @isutare412

**Comment by skgndi12** [comment]
trailling slash 에 대한 고려는 하지 않았었습니다. [관련 내용](https://stackoverflow.com/a/42193734)을 찾아보니 최근에는 trailling slash 가 있든 없든 같은 경로로 인식하는게 맞는 것 같습니다. trailling slash 유무에 관계 없이 경로를 인식하도록 수정해서 올리도록 하겠습니다.

**Comment by skgndi12** [comment]
#220 에서 작업한 내용 올렸습니다. 🙇

**Comment by 2wheeh** [comment]
@skgndi12 빠른 확인 감사합니다!
