### ISSUE TITLE
Fix wiki docs for response on error 

### ISSUE THREAD

**Issue by 2wheeh** [MovieReviewComment/Mr.C#221]
### Content

현재 Mr.C 위키에 에러 응답의 response body 스키마가 구현과 일치하지 않습니다.

```diff
{
-    "msg": "Error message"
+   "messages": ["Error message"]
}
```

이렇게 바뀌면 맞을까요?
확인 부탁드립니다 ㅎㅎ

cc @skgndi12

**Comment by skgndi12** [comment]
위키 내용 수정했습니다. 향후 작업시 참고하실 최신 API 스펙은 스웨거를 통해서 확인하시기를 부탁드립니다. 위키는 직접 싱크를 맞춰야 되기 때문에 아직 반영되지 않은 내용이 다수 있을 수 있습니다. 🙇
