### ISSUE TITLE
Build  an API Document

### ISSUE THREAD

**Issue by skgndi12** [MovieReviewComment/Mr.C#27]
- [x] Package research
- [x] Set swagger
    - [x] Authorization
- [x] Add sample code
    - [x] Request
    - [x] Response

**Comment by skgndi12** [comment]
# Swagger builder package 비교표

| Package                                                          | Stars | Open issues | Close issues | Last commit |
| ---------------------------------------------------------------- | ----- | ----------- | ------------ | ----------- |
| [tsoa](https://github.com/lukeautry/tsoa)                        | 2752  | 95          | 816          | 2023.06.23  |     
| [swagger-autogen](https://github.com/davibaltar/swagger-autogen) | 317   | 37          | 153          | 2023.06.25  |     
| [swagger-jsdoc](https://github.com/Surnet/swagger-jsdoc)         | 1536  | 30          | 150          | 2023.01.16  |     




# Swagger builder package 기능 비교

## [tsoa](https://github.com/lukeautry/tsoa)
### 장점
1. TypeScript 기반.
2. 코드로 swagger 를 관리할 수 있어 스웨거 형식을 일정하게 유지가능. (SSOT)
3. 텍스트 형식이 필요한 경우 주석으로 작성 가능.
4. 자세한 예제 코드를 풍부하게 제공.

### 단점
1. TypeScript 에 관련 설정을 추가해줘야 됨.
2. TypeScript 의 decorator 를 사용하여 기능이 구현되어 있음.(현재 decorator 는 experimental 한 기능)
3.  Controller 코드를 `tsoa` 문법에 맞게 변경해야 함.

### 예시 코드
```ts
import { Get, Route } from "tsoa";

interface PingResponse {
  message: string;
}

@Route("ping")
export default class PingController {
  @Get("/")
  public async getMessage(): Promise<PingResponse> {
    return {
      message: "pong",
    };
  }
}
```

## [swagger-autogen](https://github.com/davibaltar/swagger-autogen)
### 장점
1. Controller 의 경로들과 주석을 읽어 자동으로 통합된 파일을 완성.

### 단점
1. 주석으로 swagger 를 관리하기 때문에 수정 시 일일이 확인해서 반영해야 됨.

### 예시 코드
```js
app.post('/users', (req, res) => {
	...
	/*  #swagger.parameters['obj'] = {
			in: 'body',
			description: 'Add a user',
			schema: { $ref: '#/definitions/AddUser' }
	} */
	...
})
```

## [swagger-jsdoc](https://github.com/Surnet/swagger-jsdoc)
### 장점
1. 단순한 기능을 지원하기 때문에 설정이 편함.

### 단점
1. YAML 파일로 작성된 파일들을 읽어 하나의 파일로 통합하는 기능만을 포함.
2. 주석으로 swagger 를 관리하기 때문에 수정 시 일일이 확인해서 반영해야 됨.

### 예시 코드
```js
/**
 * @openapi
 * /:
 *   get:
 *     description: Welcome to swagger-jsdoc!
 *     responses:
 *       200:
 *         description: Returns a mysterious string.
 */
app.get('/', (req, res) => {
  res.send('Hello World!');
});
```

# 결론

1. 주석보다는 코드 기반으로 동작하는 것이 추후 관리가 용이함.
2. Star 수 , open / close issue 의 비율등의 수치

위 두 가지 사항들을 고려하여 `tsoa` 패키지를 적용하기로 결정!

**Comment by isutare412** [comment]
https://ridicorp.com/story/tspec-api-documentation/
요것도 한 번 확인해주시고 비교해주시면 좋을 것 같습니다!

**Comment by skgndi12** [comment]
# Express `Request` 의 query, path, body 에 대한 annotation 작성법

Express 의 `Request` 에 대해서 path, query, body 에 annotation 을 지정하고자 할때 다음과 같이 할 수 있다.

```ts
import { Request, Response } from 'express';

interface User {
	name: string
}

router.post('user/:id',(req: Request<{id: string}, any, User, {foo?: string}>, res: Response) => {
   // req.params.id is string
   // req.query.foo is string
   // req.body is User
   console.log(req.params.id);
   console.log(req.query.foo);
   console.log(req.body);
}
```

출력 결과
```
123
gree
{ name: 'skgndi12' }
```

참고
https://www.kindacode.com/snippet/node-js-express-typescript-req-query-type/
https://stackoverflow.com/questions/71858480/how-to-make-typescript-type-annotation-for-req-body-without-overwriting-the-orig/71858629#71858629

**Comment by skgndi12** [comment]
# Tspec 패키지 도입 검토



# Package 정보

| Package                                   | Stars | Open issues | Closed issues | Last commit |
| ----------------------------------------- | ----- | ----------- | ------------- | ----------- |
| [tspec](https://github.com/ts-spec/tspec) | 42    | 0           | 2             | 2023.06.21  |

# API Spec 작성법
API Spec 을 작성하는 방법은 
1. `Request`, `Response` 를 직접 타입에 추가하는 방법
2. Handler 를 타입에 추가하는 방법
총 두 가지 방법이 있다.

##  Request, Response 를 직접 타입에 추가했을 경우

### 예시 코드
```ts
interface Greeting {
  message: string;
}

type GreetingApiSpec = Tspec.DefineApiSpec<{
  basePath: '/api/v1/dev';
  paths: {
    '/greeting': {
      post: {
        summary: 'Greeting';
        requestBody: Greeting;
        responses: {
          201: Greeting;
        };
      };
    };
  };
}>;
```
### Open API Spec 으로 변환된 결과물
```json
{
  "info": {
    "title": "Tspec API",
    "version": "0.0.1"
  },
  "openapi": "3.0.3",
  "paths": {
    "/api/v1/dev/greeting": {
      "post": {
        "operationId": "GreetingApiSpec_post_/greeting",
        "tags": [],
        "summary": "Greeting",
        "parameters": [],
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Greeting"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Greeting": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "message"
        ]
      }
    }
  }
}
```

## Handler 를 api spec 에 등록하였을 경우

### 예시 코드
```ts
interface Greeting {
  message: string;
}

type GreetingApiSpec = Tspec.DefineApiSpec<{
  basePath: '/api/v1/dev';
  paths: {
    '/greeting': {
      post: {
        summary: 'Greeting';
        handler: typeof DevV1Controller.greeting;
      };
    };
  };
}>;
```
### Open API Spec 으로 변환된 결과물
```json
{
  "info": {
    "title": "Tspec API",
    "version": "0.0.1"
  },
  "openapi": "3.0.3",
  "paths": {
    "/api/v1/dev/greeting": {
      "post": {
        "operationId": "GreetingApiSpec_post_/greeting",
        "tags": [],
        "summary": "Greeting",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                },
                "additionalProperties": false,
                "required": [
                  "message"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Greeting"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Greeting": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "message"
        ]
      },
      "qs.ParsedQs": {
        "type": "object",
        "additionalProperties": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "$ref": "#/components/schemas/qs.ParsedQs"
            },
            {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/qs.ParsedQs"
              }
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "ParamsDictionary": {
        "type": "object",
        "additionalProperties": {
          "type": "string"
        }
      }
    }
  }
}
```

## 문제점
위에 서술한 API Spec 을 작성하는 두 가지 방법 각각 문제점이 존재

### `Request`, `Response` 를 직접 타입에 추가하는 방법
`Request`, `Response`를 OpenAPI Spec 을 위한 타입에 추가할 경우 handler 함수의 타입과 OpenAPI Spec 을 위한 타입의 싱크를 지속적으로 개발자가 직접 맞춰줘야하는 관리의 문제가 발생한다.

### Handler 를 타입에 추가하는 방법
Handler 의 타입을 `typeof` 키워드를 통해 스키마들을 등록할 경우 현재 구현된 내용을 수정해야한다. Class 메소드로 구현된 handler 함수의 타입을 class 외부에서도 참조할 수 있게 다음 두 가지 작업 중 하나가 선행되어야 한다.
1. Handler 의 메소드를 static 으로 변경
2. Handler 함수의 타입을 외부에 작성하고 이를 참조하게 변경

1번의 경우, handler 에서 class 멤버 변수에 접근할 수 없게 되는 문제가 있고, 2번의 경우는 `Request` 를 직접 타입에 등록하는 것과 마찬가지로 handler 와 OpenAPI Spec 을 위한 타입의 싱크를 개발자가 직접 맞춰줘야 하는 관리의 문제가 발생한다.


# Authentication 사용법
[공식문서](https://ts-spec.github.io/tspec/guide/authentication)에 따르면 먼저 `Tspec.GenerateParams` 에 `securityDefinition` 대한 정의가 포함되어 있어야 한다고 작성되어 있다. 그리고 `tspec` 에서 정의한 swaggeer UI 용 middleware 에 첫번째 인자로 앞서 정의한 `securityDefinition` 을 넘겨 UI 에 반영할 수 있다.

## 예시 코드
```ts
// server.ts
import express from 'express';
import { Tspec, TspecDocsMiddleware } from 'tspec';

import * as controller from './controller'

const tspecParams: Tspec.GenerateParams = {
  openapi: {
    securityDefinitions: {
      jwt: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
      },
    },
  },
};

const initServer = async () => {
  const app = express()
  app.get('/my', controller.getMyInfo);
  app.use('/docs', await TspecDocsMiddleware(tspecParams));
  app.listen(3000);
}
initServer();


// controller.ts
export type UserApiSpec = Tspec.DefineApiSpec<{
  security: 'jwt',
  paths: {
    '/my': {
      get: {
        summary: 'Get my info',
        handler: typeof getMyInfo
      },
    },
  }
}>;

```

# 결론
조사를 해보며 다음 세가지 사항 때문에 이 패키지 도입을 안 하는 것이 좋다고 판단했음.
1. 이제 막 출시되었고, 많은 사람들이 사용하고 있지 않기 때문에 예상치 못한 문제가 발생할 수 있음.
2. SSoT 가 이 패키지가 내세우는 가장 큰 장점인데 막상 도입하려고 보니 OpenAPI Spec 을 위한 타입과 handler 함수의 타입 간 싱크를 맞춰야 하는 문제가 있어 장점이 퇴색됨.
3. 기능을 사용하기 위해 설정이 아닌 코드에서 메타데이터를 선언해야함.

위 세 가지 사항으로 인해 패키지 도입은 추후로 미루거나 하지 않는 것이 좋다고 생각함.

**Comment by isutare412** [comment]
조사하느라 고생 많으셨습니다! 그럼 `tsoa` 로 가시는 건가요?

**Comment by skgndi12** [comment]
~~네 패키지는 `tsoa` 를 사용할 것 같습니다.~~ `tsoa` 의 패키지의 구조가 사용하기에는 다소 까다로운 면이 많고, `tspec` 패키지의 문제였던  타입 간 싱크 문제를 해결할 방법을 발견해서 `tspec` 패키지를 사용할 것 같습니다. 자세한 내용은 PR 에서 상술하도록 하겠습니다.
