### ISSUE TITLE
Client IP can be spoofed by setting specific HTTP headers

### ISSUE THREAD

**Issue by skgndi12** [MovieReviewComment/Mr.C#34]
HTTP request header에 특정 헤더 키를 조작하면 access log 에 원하는 IP 를 남길 수 있음.

cURL 예시)
```
curl --request POST \
  --url http://localhost:8080/api/v1/dev/greeting \
  --header 'content-type: application/json' \
  --header 'x-real-ip: 1.2.3.4' \
  --data '{"test": "test"}'
```
Access log 의 IP 가 `1.2.3.4` 로 조작된 것을 확인.
```
[2023-06-04 11:56:48][http]: Access log {"deployment":"local","method":"POST","url":"/api/v1/dev/greeting","addr":"1.2.3.4","proto":"http/1.1","contentLength":"22","userAgent":"vscode-restclient","statusCode":200,"bodyBytes":"26","elapsedMs":1,"contentType":"application/json"}
```

**Comment by isutare412** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#selecting_an_ip_address

> Trusted proxy count: The count of reverse proxies between the internet and the server is configured. The X-Forwarded-For IP list is searched from the rightmost by that count minus one. (For example, if there is only one reverse proxy, that proxy will add the client's IP address, so the rightmost address should be used. If there are three reverse proxies, the last two IP addresses will be internal.)

참고 바랍니다.

**Comment by isutare412** [comment]
텔레그램 웹훅 테스트
