### ISSUE TITLE
Add PostgreSQL client

### ISSUE THREAD

**Issue by isutare412** [MovieReviewComment/Mr.C#42]
PostgreSQL 을 이용할 수 있는 adapter layer 를 설계합니다.

- [x] ORM 사용할지 말지 정하기.
- [x] ORM 을 사용한다면 여러 기술들 비교 및 정하기.
- [x] 여러 repository 를 아우르는 transaction 에 대한 공부.
- [x] #53
- [x] Versioned schema migration 에 대해 알아보고 적용.

**Comment by skgndi12** [comment]
## Raw Query

**장점:**
1. 질의를 직접 작성하고 관리할 수 있어 명확한 제어가 가능합니다.
2. 성능 면에서 추상화된 도구보다 높은 성능을 달성할 수 있습니다.
3. 직접 질의를 작성하는 것이 유연성 면에서 다른 추상화된 도구보다 우수할 수 있습니다.

**단점:**
1. 데이터베이스 구조와 SQL에 대한 깊은 이해가 필요합니다.
2. SQL Injection과 같은 보안 문제에 대한 처리가 필요하며, 이를 위한 로직을 직접 구현해야 합니다.
3. 데이터 조작 시 여러 계층의 데이터와 섞여 복잡성이 증가할 수 있습니다.
4. 데이터베이스에 종속적인 코드로 유지보수 어려움이 있을 수 있습니다.

## Query Builder

**장점:**
1. 문자열 대신 프로그래밍 언어의 메소드나 함수를 사용해 구현하므로, 유지보수가 더 쉽습니다.
2. 생성되는 질의 내용이 더 투명하게 드러나며, 연산의 의도와 결과를 이해하기 쉽습니다.
3. 여러 관계형 DBMS를 추상화하여 지원하므로, DBMS 변경 시에도 도움이 됩니다.
4. 쿼리의 재사용성이 높아 개발 생산성을 향상시킵니다.

**단점:**
1. 데이터베이스 구조와 기능에 대한 학습이 필요하며, 어떻게 동작하는지 이해하는 데도 시간이 필요합니다.
2. 데이터베이스와 어플리케이션 데이터의 매핑을 정의해야 합니다.
3. 복잡한 질의나 조인을 다룰 때 SQL을 사용하는 것보다 제한적일 수 있습니다.
4. 추상화된 도구로 인해 성능 저하 가능성이 있습니다.

## ORM (Object-Relational Mapping)

**장점:**
1. 데이터 시스템 접근과 조작에 도움을 주며, 데이터베이스와 객체 간의 변환을 자동으로 처리합니다.
2. Boilerplate 코드가 줄어들어 개발 생산성을 향상시킵니다. Migration 도구를 포함할 수 있어 스키마 변경 관리도 간소화됩니다.
3. 다양한 객체와 관계형 데이터베이스 간의 매핑을 자동화하므로, 유지보수와 확장성이 향상됩니다.
4. 객체 지향적인 코드 작성이 가능하므로 응용 프로그램의 설계와 유지보수가 용이합니다.

**단점:**
1. 높은 추상화로 인해 복잡성이 증가하며, 복잡한 작업에서 문제를 일으킬 수 있습니다.
2. ORM과 질의 언어에 대한 이해 없이 사용하면 디버깅과 성능 문제를 야기할 수 있습니다.
3. 객체와 관계의 패러다임 불일치로 인해 복잡한 질의나 복잡한 관계에 대한 처리가 어려울 수 있습니다.
4. 데이터베이스의 특정 기능을 활용하기 위해 ORM을 빠져나와야 하는 경우가 있을 수 있습니다.

# 결론
위의 장점과 단점을 종합해 본 결과, 현재 프로젝트에서는 ORM을 사용하는 것이 가장 적절해 보입니다.
1. Raw query나 query builder를 사용할 경우, object-relation 맵핑을 직접 구현해야 합니다. 이로 인해 전체 프로젝트 진행 속도가 느려질 우려가 있습니다.
2. 복잡한 질의나 조인이 없는 경우에는 ORM의 복잡성이 큰 영향을 미치지 않을 것으로 예상됩니다.

따라서, 현재 프로젝트의 특성을 고려하여 위의 이유로 ORM을 사용하기로 결정하였습니다.

# 참고 내용
- [Prisma Data Guide: Comparing SQL Query Builders and ORMs](https://www.prisma.io/dataguide/types/relational/comparing-sql-query-builders-and-orms)
- [Object-relational impedance mismatch - Wikipedia](https://en.wikipedia.org/wiki/Object%E2%80%93relational_impedance_mismatch)
- [Object-Relational Impedance Mismatch - Medium Article](https://medium.com/booleanbhushan/object-relational-impedance-mismatch-28fc2440dee4)

**Comment by skgndi12** [comment]
# Package 비교표

| Package                                             | Stars | Open issues | Close issues | Last commit |
| --------------------------------------------------- | ----- | ----------- | ------------ | ----------- |
| [Prisma](https://github.com/prisma/prisma)          | 33.5k | 2731        | 6265         | 2023.08.30  |
| [TypeORM](https://github.com/typeorm/typeorm)       | 32k   | 2052        | 5594         | 2023.08.20  |
| [Sequelize](https://github.com/sequelize/sequelize) | 28.3k | 782         | 9351         | 2023.08.30  |

# Prisma

## 특징
- 비교적 최근에 출시된 DB toolkit
- Prisma schema로 모델을 선언하며, 선언적 데이터 모델 정의와 마이그레이션을 지원
- Prisma Client: Prisma schema를 기반으로 타입 안정성을 보장하는 쿼리 빌더 제공
- Prisma Migrate: Prisma schema 기반의 마이그레이션 시스템
- Prisma Studio: 데이터베이스를 직접 조작하고 볼 수 있는 GUI 도구

## 장점
- 데이터 생성 및 조회에 강력한 타입 안정성을 보장 (중첩된 데이터 생성 및 조회 포함)
- 다양한 데이터베이스 지원 (PostgreSQL, MySQL, MSSQL 등)
- SSoT(Single source of truth)을 보장하기 위해 Prisma schema 기반으로 타입 정보 생성
- 새로운 기능 및 업데이트가 지속적으로 이루어짐

## 단점
- 다른 ORM으로 마이그레이션하기 어려울 수 있음 (자체 스키마 형식 사용)
- 패키지 크기가 크고 고급 기능이 부족할 수 있음

## 예시 코드
```ts
// schema.prisma
model UserModel {
  id    BigInt @id @default(autoincrement())
  name  String @db.VarChar(64)
  email String @db.VarChar(64)
}

// user.repository.ts
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const user = await prisma.user.create({
    data: {
        name: 'John Doe',
        email: 'john@example.com',
    },
});
```

# TypeORM

## 특징
- Hibernate 영향을 받은 TypeScript 기반의 ORM
- Active Record 및 Data Mapper 패턴 지원

## 장점
- 데이터 생성에 대한 타입 안정성 보장 (중첩된 데이터 생성 포함)
- 다양한 데이터베이스 지원 (MySQL, PostgreSQL, SQLite 등)
- Active Record 및 Data Mapper 패턴 모두 지원하여 유연한 개발 가능

## 단점
- 데이터 조회에 대한 타입 안정성은 부분적 (중첩된 데이터 조회에 추가 작업 필요)
- 초기 학습 곡선이 가파름
- 설정이 복잡할 수 있음

## 예시 코드
```ts
// user.entity.ts
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity()
export class User {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column()
    email: string;
}

// user.repository.ts
const firstUser = await conn
    .getRepository(User)
    .createQueryBuilder("user")
    .where("user.id = :id", { id: 1 })
    .getOne();
```

# Sequelize

## 특징
- Promise 기반 Node.js ORM
- Active Record 패턴 지원
- 다양한 데이터베이스 지원 (PostgreSQL, MySQL, SQLite 등)

## 장점
- 다양한 데이터베이스 지원
- 기존에 많이 사용되고 있는 패키지로 레퍼런스가 풍부

## 단점
- 데이터 생성 및 조회 모두 타입 안정성 부족
- 프로젝트 진행이 둔화되어 개발이 제대로 되고 있지 않음

## 예시 코드
```ts
const { Sequelize, Model, DataTypes } = require('sequelize');

const sequelize = new Sequelize('database', 'username', 'password', {
  dialect: 'mysql',
});

class User extends Model {}
User.init({
  name: DataTypes.STRING,
  email: DataTypes.STRING,
}, {
  sequelize,
  modelName: 'user',
});

User.hasMany(Photo);
Photo.belongsTo(User);

(async () => {
  await sequelize.sync({ force: true });
  const user = await User.create({
    name: 'John Doe',
    email: 'john@example.com',
  });
  const photo = await user.createPhoto({
    url: 'example.com/photo.jpg',
  });
})();
```

# 결론

세 가지 패키지를 비교해보면, Prisma가 데이터 생성과 조회 모두에 강력한 타입 안정성을 제공하며, SSoT를 유지하면서 다양한 데이터베이스 지원과 지속적인 업데이트로 인해 가장 좋은 선택이 될 것으로 판단.

**Comment by isutare412** [comment]
https://github.com/MovieReviewComment/Mr.C/issues/42#issue-1771183386

우선순위를 변경하였으니 https://github.com/MovieReviewComment/Mr.C/issues/53 보다 TX 공부 및 설계를 먼저 진행해주세요.
길어진다 싶으면 https://github.com/MovieReviewComment/Mr.C/issues/53 처럼 별도의 이슈로 빼도 좋습니다.

**Comment by skgndi12** [comment]
# 트랜잭션 (Transaction)

트랜잭션은 데이터베이스 관리 시스템(DBMS)에서 실패 또는 성공이 보장되어야 하는 연산들을 논리적으로 묶은 단위입니다.

## ACID

관계형 데이터베이스에서 안정성과 신뢰성을 보장하기 위해 트랜잭션에서 지켜져야 하는 4가지 핵심 원칙을 나타내는 약어입니다.

### 원자성 (Atomicity)

**원자성**은 트랜잭션을 원자적인 단위로 간주하는 원칙입니다. 트랜잭션 내의 모든 작업은 성공적으로 완료되거나 아무것도 반영되지 않아야 합니다. 즉, 트랜잭션은 부분적으로 완료되어서는 안 되며, 어떤 부분도 데이터베이스에 영향을 미치지 않은 채로 실패해야 합니다.

#### 트랜잭션 (Transaction) 의 상태 및 처리 과정

1. **Active (활동 또는 시작):** 트랜잭션은 활동 상태에서 시작됩니다. 이 단계에서 트랜잭션은 아직 어떤 데이터베이스 작업도 수행하지 않은 상태입니다. 즉, 트랜잭션이 시작되었지만 아직 어떤 데이터 변경도 일어나지 않았습니다.
    
2. **Partially Committed (부분 완료):** 트랜잭션은 데이터베이스 작업을 수행하고 커밋 직전의 상태입니다. 이 상태에서 트랜잭션은 모든 작업을 완료했지만 아직 커밋되지 않았습니다. 다른 트랜잭션은 이 트랜잭션에서 수행한 작업을 볼 수 없습니다. 트랜잭션의 모든 변경 사항은 커밋되기를 기다리고 있습니다.
    
3. **Committed (완료):** 트랜잭션은 성공적으로 완료되고 커밋된 상태입니다. 이 단계에서 트랜잭션에서 수행한 모든 변경 사항은 영구적으로 데이터베이스에 반영되었습니다. 다른 트랜잭션은 이 트랜잭션에서 수행한 작업을 확인할 수 있습니다. 커밋된 트랜잭션은 더 이상 롤백할 수 없습니다.
    
4. **Failed (실패):** 트랜잭션은 실패하거나 오류가 발생한 상태입니다. 이 단계에서 트랜잭션이 어떤 이유로든 중단되었습니다. 실패한 트랜잭션은 데이터베이스에 영향을 미치지 않으며, 트랜잭션이 실패하기 전의 상태로 되돌릴 수 있습니다.
    
5. **Aborted (롤백):** 롤백은 실패한 트랜잭션을 이전 상태로 복구하는 프로세스를 나타냅니다. 트랜잭션의 상태가 롤백된 후에는 해당 트랜잭션이 시작하기 전의 상태로 되돌아갑니다. 즉, 롤백을 통해 트랜잭션의 모든 변경 사항이 취소되어 데이터베이스에는 아무런 영향을 미치지 않게 됩니다.

![States-of-Transaction-in-DBMS](https://github.com/MovieReviewComment/Mr.C/assets/41230920/b9629781-c6d3-4578-b959-517608b4ca5d)

### 일관성 (Consistency)

**일관성**은 트랜잭션이 데이터베이스를 일관된 상태로 유지하는 원칙입니다. 트랜잭션이 시작하기 전과 끝난 후에도 데이터베이스는 일관된 규칙과 제약 조건을 따라야 합니다. 다시 말해, 트랜잭션이 완료된 후에 데이터베이스는 어떤 무결성 제약 조건도 위반해서는 안 됩니다.

#### 무결성 제약 조건 (Integrity Constraints)

무결성 제약 조건은 데이터베이스 내의 데이터의 무결성과 일관성을 유지하기 위한 규칙 및 제약 사항을 나타냅니다.

1. **개체 무결성 (Entity Integrity):** 주요 테이블의 각 행에 대한 기본 키(PK) 값이 고유하고 NULL이 아니어야 합니다. 중복된 레코드를 방지하고 데이터의 일관성을 유지하는데 관여합니다.

2. **참조 무결성 (Referential Integrity):** 외래 키(FK)와 관련된 테이블 간의 관계를 유지하기 위한 규칙을 정의합니다. 외래 키는 다른 테이블의 기본 키를 참조하며, 데이터 간의 관계를 유지하고 데이터 무결성을 보장하는데 중요한 역할을 합니다.

3. **도메인 무결성 (Domain Integrity):** 각 열(속성)의 값이 정의된 도메인(데이터 유형)에 속하는지 확인하는 제약 조건입니다. 데이터가 해당 도메인에 맞는지 검증합니다.

4. **사용자 정의 무결성 (User-Defined Integrity):** 데이터베이스 관리자 또는 사용자가 정의한 특정 비즈니스 규칙을 나타냅니다. 데이터의 일관성을 유지하기 위해 사용됩니다.

### 고립성 (Isolation)

**고립성**은 복수의 트랜잭션이 서로 간섭하지 않도록 하는 원칙입니다. 한 트랜잭션의 작업은 다른 트랜잭션에게 보이지 않아야 하며, 각 트랜잭션은 데이터베이스에 독립적으로 작업하는 것처럼 보여야 합니다. 이 원칙은 다른 트랜잭션의 작업이 진행 중인 트랜잭션에 영향을 미치지 않는 것을 보장합니다.

#### 고립성 레벨 (Isolation Levels)

다양한 고립성 레벨은 트랜잭션 간의 격리 정도를 조절합니다:

1. **Read Uncommitted (미완료 읽기):** 가장 낮은 고립성 레벨로, 다른 트랜잭션의 변경 사항을 무시하고 읽을 수 있으며, 데이터의 무결성과 일관성이 보장되지 않습니다.

2. **Read Committed (완료 읽기):** 커밋된 데이터만 읽을 수 있으며, 다른 트랜잭션의 변경 사항은 읽을 수 없습니다.

3. **Repeatable Read (반복 가능한 읽기):** 같은 쿼리를 반복 실행해도 결과가 일관되며, 커밋되지 않은 데이터를 읽을 수 없습니다.

4. **Serializable (직렬화 가능):** 가장 높은 격리 수준으로, 모든 트랜잭션을 순차적으로 실행한 것과 같은 결과를 보장합니다. 가장 높은 데이터 무결성과 일관성을 달성할 수 있지만, 동시성은 감소합니다.

#### 트랜잭션 격리 수준 관려 이슈와 예시

**Dirty Read**
- Dirty read(더티 리드)는 트랜잭션 A가 아직 커밋되지 않은 데이터를 읽었을 때 발생합니다.
- 예시: 트랜잭션 A가 금액을 이체하려고 할 때, 트랜잭션 B가 해당 계좌 잔액을 변경하고 아직 커밋하지 않은 경우, 트랜잭션 A가 잘못된 잔액을 읽을 수 있습니다.

**Non-Repeatable Read**
- Non-repeatable read(비반복 가능한 읽기)는 트랜잭션 A가 동일한 데이터를 두 번 읽을 때, 두 번의 읽기 사이에 데이터가 변경되는 경우에 발생합니다.
- 예시: 트랜잭션 A가 주문 정보를 조회하고, 그 후 다시 같은 주문 정보를 조회하는 동안, 다른 트랜잭션 B가 해당 주문을 취소한 경우, 트랜잭션 A가 두 번의 조회 결과가 다를 수 있습니다.

**Phantom Read**
- Phantom read(팬텀 리드)는 트랜잭션 A가 동일한 쿼리를 두 번 실행했을 때 결과 집합에 다른 행이 추가되거나 제거되는 경우에 발생합니다.
- 예시: 트랜잭션 A가 특정 범위의 주문 목록을 조회한 후, 다시 같은 범위의 주문 목록을 조회하는 동안, 다른 트랜잭션 B가 새로운 주문을 생성한 경우, 두 번의 조회 결과가 다를 수 있습니다.

**Serialization Anomaly**
- Serialization Anomaly(직렬화 이상 현상)는 여러 트랜잭션이 동시에 실행될 때, 그 실행 순서에 따라 결과가 일관성이 없게 되는 현상을 의미합니다. 직렬화 이상 현상은 높은 격리 수준을 사용하여 방지하며, 데이터베이스 시스템은 여러 트랜잭션 간의 의존성을 관리하여 일관성을 유지합니다.
- 예시: 두 트랜잭션 A와 B가 동시에 실행되고 서로 다른 순서로 커밋된 경우, 결과가 일관성 없이 나타날 수 있습니다.

### 지속성 (Durability)

**지속성**은 트랜잭션이 완료된 후에 변경된 데이터가 영구적으로 저장되어야 함을 나타내는 원칙입니다. 시스템 장애 또는 전원 손실과 같은 문제가 발생하더라도, 트랜잭션으로 인해 변경된 데이터는 손실되지 않아야 합니다.
