### ISSUE TITLE
Reconstruct ui directory

### ISSUE THREAD

**Issue by 2wheeh** [MovieReviewComment/Mr.C#48]
### Content
배포하게 될 프론트 페이지들이 추가될 경우 (ex. admin 페이지)를 고려하여, 여러 프로젝트를 관리하기 적합한 구조로 ui 디렉토리를 재구성합니다.

### Task
- [x] #56
- [x] #57
- [x] #58

**Comment by 2wheeh** [comment]
vscode 사용 시 yarn berry 가 관리하는 패키지에서 Typescript 가 올바르게 설정되기 위해서 @yarnpkg/sdks 의 설치가 필요합니다. (https://yarnpkg.com/getting-started/editor-sdks)

현재 @yarnpkg/sdks 와 [prettier latest stable 버전인 3.0.0](https://prettier.io/versions.html) 의 호환에 이슈가 있습니다. format on save 실행 시 vscode 가 무한 로딩에 빠지는 이슈입니다. (https://github.com/prettier/prettier-vscode/issues/3068)

따라서 ui 패키지 prettier 의존성의 시멘틱을 ^2로 설정합니다.

**Comment by 2wheeh** [comment]
> vscode 사용 시 yarn berry 가 관리하는 패키지에서 Typescript 가 올바르게 설정되기 위해서 @yarnpkg/sdks 의 설치가 필요합니다. (https://yarnpkg.com/getting-started/editor-sdks)
> 
> 현재 @yarnpkg/sdks 와 [prettier latest stable 버전인 3.0.0](https://prettier.io/versions.html) 의 호환에 이슈가 있습니다. format on save 실행 시 vscode 가 무한 로딩에 빠지는 이슈입니다. ([prettier/prettier-vscode#3068](https://github.com/prettier/prettier-vscode/issues/3068))
> 
> 따라서 ui 패키지 prettier 의존성의 시멘틱을 ^2로 설정합니다.

-  `pnp` 프로젝트에서 `vscode` 의 `ts`, `prettier`, ...  동작을 위한 세팅이며, `.vscode` 가 `ui/` 에 존재하고 이 경로를 루트로 `vscode` 를 실행하여 작업해야합니다.
- 이는 현재 `Mr-C.code-workspace` 를 이용해 `workspace(vscode)` 로 작업하는 환경과 맞지 않습니다 
   (#52)
- `yarn berry` 를 택한 이유가 `ui/` 구조를 위한 `workspace(yarn)` 기능 인 점을 상기하며, `node_linker` 는 `pnp` 가 아닌 `node_modules` 로 진행하겠습니다.

**Comment by 2wheeh** [comment]
아래의 구조로 작업 중 입니다.
```
Mr.C
├── MR-C.code-workspace
├── .github/
│   ├── workflows/
│   │   └── run-test.yaml
│   └── pull_request_template.md
├── api/
│   └── ...
└── ui/
    ├── .yarn
    ├── tsconfig.base.json
    ├── pakcage.json
    └── packages/
        ├── package-a (next)/
        │   ├── tsconfig.json
        │   ├── tailwind.config.js
        │   └── ...
        ├── package-b (design-system)/
        │   ├── tsconfig.json
        │   ├── tailwind.config.js
        │   └── ...
        ├── package-c (utils)/
        │   ├── tsconfig.json
        │   └── ...
        └── ...(more packages)
```
각 서브 패키지들은 아래처럼 구성할 예정입니다. 
1. package-a: `Mr.C` 의 클라이언트 웹 서비스 `nextjs` 패키지 
    - 디렉토리 명: `mr-c` <- 구매가능한 `mrc` 도메인이 없어서 `mr-c` 로 도매인 구매 예정입니다.
    - 패키지 명: `@mrc/mr-c`
2. package-b: `Mr.C/ui` 의 공용 컴포넌트, 디자인 시스템 패키지
    - 디렉토리 명: `common-components`
    - 패키지 명: `@mrc/common-components` 
3. package-c: `Mr.C/ui`의 공용 유틸 함수, 훅 패키지
    - 디렉토리 명: `common-utils`
    - 패키지 명: `@mrc/common-utils` 
    
 패키지 명 prefix의 경우, 각 서브 패키지의 publish 를 고려하면 organization 이름과 맞추어 `@MovieReviewComment/` 이 되어야 합니다. 하지만 레지스트리에 서브 패키지를 배포할 계획이 없으므로 편의를 위해 `@mrc/` 로 정합니다.

**Comment by isutare412** [comment]
> 디렉토리 명: mr-c <- 구매가능한 mrc 도메인이 없어서 mr-c 로 도매인 구매 예정입니다.

도메인은 나중에 서비스에 사용할 도메인을 말하는게 맞나요?

**Comment by 2wheeh** [comment]
> > 디렉토리 명: mr-c <- 구매가능한 mrc 도메인이 없어서 mr-c 로 도매인 구매 예정입니다.
> 
> 도메인은 나중에 서비스에 사용할 도메인을 말하는게 맞나요?

네 가비아에서 조회해보니 mrc 가 들어가는 도메인은 모두 이미 등록되어있어서, mr-c 로 사용해야할 것 같습니다.
패키지명은 도메인 구입 후 도메인 전체를 반영하는 방법도 있을 것 같습니다.
ex. `mr-c.app` 구매 시 디렉토리명: `mr-c.app` 패키지명: `@mrc/mr-c.app`

**Comment by isutare412** [comment]
도메인 같은 경우 API, UI 모듈의 배포 상태에 따라 고려가 필요해서 먼저 사지 말아주세요.

**Comment by 2wheeh** [comment]
네 알겠습니다 ~

**Comment by 2wheeh** [comment]
한 Issue 로 다루기에 내용이 많아지는 것 같아 서브 태스크를 별도의 Issue 로 나눕니다. (#56, #57)
