### ISSUE TITLE
Enhancement of the HTTP Error Handling System

### ISSUE THREAD

**Issue by skgndi12** [MovieReviewComment/Mr.C#71]
- [x] Return appropriate status code and message based on the caught exception

**Comment by isutare412** [comment]
필요 조건 적어둡니다.
- Repository 레이어에서 exception 을 발생시킬 때는 404 와 같은 직접적인 HTTP status code 는 지양. ( 예를 들자면, 404 대신 NOT_FOUND enum 을 사용해야 함)
- HTTP 레이어에서 exception 타입을 체크할 땐 `RepositoryError` 를 직접 import 하면 안됨. (HTTP 레이어와 repository 레이어 사이의 강한 결합 방지)

**Comment by skgndi12** [comment]
https://gist.github.com/RWOverdijk/6cef816cfdf5722228e01cc05fd4b094

**Comment by skgndi12** [comment]
# 기존 에러 처리

## 내용
1. 각 레이어(controller/service/repository)마다의 별도의 에러를 정의(e.g `RepositoryError`).
2. 에러를 캐치하는 곳에서 내용을 보고 자신의 레이어에 맞는 형태로 재가공하거나 그대로 던짐.

## 문제점 
과정이 필요 이상으로 복잡하고 그로 인해 얻어지는 이득은 크게 없음.

# 변경된 에러 처리

## 내용
기존 에러 처리의 과정을 보다 간단하고 명료하게 하기 위해 다음과 같이 수정.

1. 모든 레이어(controller/service/repository 등등)에서 분류할 수 있는 모든 에러를 `CustomError` 로 통일. 
2. `CusomError` 에 에러 코드로 분기하여 알맞는 상태 코드를 반환하는 기능 추가.

  
## 문제점
Request / Response 를 validate 하는 패키지에서 던지는 에러는 이미 상태 코드가 설정되어 있음. 이 에러를 `CustomError` 로 변환하는 것을 고려한다면 상태 코드에 대한 내용이 추가되어야 함.

## 해결 방안

### 1. `CustomError` 에 HTTP 에러에 대한 내용을 추가

- 장점:  새로운 통신 프로토콜 레이어가 생긴다 하더라도 같은 방식으로 `CustomError` 에 프로토콜의 에러 코드와 코드를 변환하는 기능만 추가하면 됨.

- 단점: `CustomError` 가 HTTP 의 에러 코드까지 알고 있게됨.

### 2. HTTP 응답을 위한 별도의 에러를 정의 후 `CustomError` -> `HttpError` 로 변환하는 과정이 추가

- 장점: `CustomError` 에서 HTTP 의 에러 코드 내용이 필요없게 됨.

- 단점: 새로운 통신 프로토콜 레이어가 생기면 매번 그에 맞는 프로토콜용 에러를 정의하고 모든 에러를 그에 맞게 변환하는 과정이 필요하게 됨.

# 결론
[해결 방안](#해결-방안)을 놓고 보았을때 `CustomError` 가 HTTP 의 에러 코드에 대해 알고있는 것이 큰 문제가 아니라고 판단. 반대로, `HttpError` 를 정의하여 변환하는 과정이 개발 공수만 늘어나고 큰 이득은 없다고 생각했음. 따라서 `CustomError` 에 HTTP 의 에러 코드를 추가하도록 결정.
